### ISSUE TITLE
opensuse tumbleweed

### ISSUE THREAD

**Issue by darylkuchay** [mustafaozhan/GoogleIntegratedSystemConky#10] opened 2018-10-30 20:02 UTC
Thank you for sharing your project. Went through the pre install well. Python pip installed without errors a number of packages. I chose the ubuntu line to copy from. Did google email address and password in config.xml. Upon running I see:

sh-4.4$ sh ~/.config/GoogleIntegratedSystemConky/gisc.sh start
```
starting
conky: Syntax error (conkyrc:2: '=' expected near 'yes') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: desktop window (1c0000b) is subwindow of root window (24b)
conky: drawing to desktop window
conky: drawing to double buffer
conky: statfs64 '/data': No such file or directory
conky: forked to background, pid is 17682
sh-4.4$ conky: Syntax error (conkyKeepRc:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: desktop window (1c0000b) is subwindow of root window (24b)
conky: window type - override
conky: drawing to created window (0x5000001)

conky: drawing to double buffer
conky: forked to background, pid is 17684

conky: statfs64 '/data': No such file or directory
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  164
  Current serial number in output stream:  165
  File "/usr/bin/gcalcli", line 199
    print "ERROR: Missing module - %s" % e.args[0]
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("ERROR: Missing module - %s" % e.args[0])?
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  4 (RenderCreatePicture)
  Serial number of failed request:  454
  Current serial number in output stream:  460
^C
```
 Anything I missed or overlooked?

**Comment by mustafaozhan** [comment] 2018-10-31 18:39
Hello,

are you sure that you installed the [gcalcli](https://github.com/insanum/gcalcli) succesfully ? It seems configuration file can not execute it

**Comment by darylkuchay** [comment] 2018-11-01 11:04
```
daryl@G7:~> pip install gcalcli
Requirement already satisfied: gcalcli in /usr/lib/python3.6/site-packages (3.4.0)
Requirement already satisfied: python-dateutil in /usr/lib/python3.6/site-packages (from gcalcli) (2.7.5)
Requirement already satisfied: python-gflags in /usr/lib/python3.6/site-packages (from gcalcli) (3.1.2)
Requirement already satisfied: httplib2 in /usr/lib/python3.6/site-packages (from gcalcli) (0.11.3)
Requirement already satisfied: google-api-python-client in /usr/lib/python3.6/site-packages (from gcalcli) (1.7.4)
Requirement already satisfied: oauth2client<=1.4.12 in /usr/lib/python3.6/site-packages (from gcalcli) (1.4.12)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.6/site-packages (from python-dateutil->gcalcli) (1.11.0)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /usr/lib/python3.6/site-packages (from google-api-python-client->gcalcli) (3.0.0)
Requirement already satisfied: google-auth-httplib2>=0.0.3 in /usr/lib/python3.6/site-packages (from google-api-python-client->gcalcli) (0.0.3)
Requirement already satisfied: google-auth>=1.4.1 in /usr/lib/python3.6/site-packages (from google-api-python-client->gcalcli) (1.5.1)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python3.6/site-packages (from oauth2client<=1.4.12->gcalcli) (0.4.4)
Requirement already satisfied: pyasn1_modules>=0.0.5 in /usr/lib/python3.6/site-packages (from oauth2client<=1.4.12->gcalcli) (0.2.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/lib/python3.6/site-packages (from oauth2client<=1.4.12->gcalcli) (4.0)
Requirement already satisfied: cachetools>=2.0.0 in /usr/lib/python3.6/site-packages (from google-auth>=1.4.1->google-api-python-client->gcalcli) (2.1.0)
```

**Comment by mustafaozhan** [comment] 2018-11-02 09:51
Hello,

Finally I figured out your problem. Yes you installed gcalcli but the problem is you install the version with python 3. Please remove it and install with python 2. It is not working because syntax differences between python 2 and python 3. Please let me know after if it will work than I can close the issue :)

**Comment by darylkuchay** [comment] 2018-11-02 16:17
Thank you for your insight. 

`pip3 uninstall gcalcli `
`pip2 install gcalcli`
and
`sh ~/.config/GoogleIntegratedSystemConky/gisc.sh start`

did open a browser to allow to to authorize. 

`sudo killall conky `
and
`sh ~/.config/GoogleIntegratedSystemConky/gisc.sh start`

and I get the flash on the desktop and conky runs in background or not on main window. 

Am I up to a usable conky config for plasma 5 at this point? If so please indicate as such and then close as install looks to have completed.

**Closed** 2018-11-06 13:12 UTC
Labels: installation problem

**Comment by mustafaozhan** [comment] 2018-11-08 10:16
Hello,

I am using this configuration on XFCE desktop environment. I know that there is differences in conky config when you switch the desktop environment. I do not use KDE so that's why I can not test it. I highly suggest to you that check some of KDE conky config especially
`#Window Specification
own_window no
own_window_type normal
own_window_transparent yes
own_window_argb_visual yes`
this is a part of conkyrc file and test it with different variations. It will work. In the past I did same for Gnome Shell
